- name: Test
  hosts: switch01
  connection: ansible.netcommon.network_cli
  gather_facts: no
  collections: 
    - arista.eos

  tasks:
    - name: Merge provided configuration with device configuration
      arista.eos.eos_acls:
        config:
        - afi: ipv4
          acls:
          - name: test1
            aces:
            - sequence: 35
              grant: deny
              protocol: ospf
              source:
                subnet_address: 20.0.0.0/8
              destination:
                any: true
        state: merged
